### ISSUE TITLE
unifiedGenotyper_5g.snpEFF.vcf.gz error

### ISSUE THREAD

**Issue by phuchoang1012** [ExpressionAnalysis/CNV_Radar#4]
Hi,
Thanks for developing the tool. When I tried to run CNV_Radar.r, I recevied the followng error: 

zip: tumor.unifiedGenotyper_5g.snpEFF.vcf.gz: No such file or directory
tumor.bqsr.unifiedGenotyper_5g.snpEFF.vcf.gz: No such file or directory
Error in read.table(file = pipe(paste0("zless ", params$sample, params$vcf)),  : 
  no lines available in input
Calls: readVCF -> read.table
Execution halted

Am I supposed to provide some snpEFF vcf file? If so this was not desbcribed in README file. Any examples of these vcf file? 

Thank you!

**Comment by rsteinfe1** [comment]
Hi all,
I'm currently trying to set this up right myself and it looks like that the vcf files need to be annotated with SnpSift 
using dbSNP. 
My dbSNP VCF files looks like this:
1	10177	rs367896724	A	AC	.	.	RS=367896724;RSPOS=10177;dbSNPBuildID=138;SSR=0;SAO=0;VP=0x050000020005130026000200;GENEINFO=DDX11L1:100287102;WGT=1;VC=DIV;R5;ASP;G5A;G5;KGPhase3;CAF=0.5747,0.4253;COMMON=1;TOPMED=0.76728147298674821,0.23271852701325178
SnpSift adds the info tag of matching SNPs to SNPs you have called with GATK. 
CNV_Radar.r parses the info field and selects only those SNPs that have COMMON=1 and discards the rest.

I further noticed that files need to be named [id].unifiedGenotyper_5g.snpEFF.vcf.gz (it requires this suffix). 
If you don't want to rename your files, you could change this by editing the following line in CNV_Radar.r:

vcf <- list(VarPROWL=".all_snv.vcf.gz", GATK=".unifiedGenotyper_5g.snpEFF.vcf.gz")
I think this is line 122. 

Let me know if that helps. 

Best,
 Robert

**Comment by jkstrat** [comment]
Hi all,

This is an issue that we were aware of and were working on a solution. Unfortunately the v1.1.0 release was designed mostly for internal use and was heavily geared toward the VarPROWL variant caller used internally at EA Genomics as noted by rsteinfe1 in the comment above. We have just released v1.2.0 that has an updated function for reading in VCF files. So as long as the VCF is formatted with v4.2 conventions it should be able to be used as an input. 

@janrehker We agree that examples on how to run the software would be very helpful. As such we have created a new vignette for that purpose: https://github.com/ExpressionAnalysis/CNV_Radar/blob/master/Vignette/vignette.md. There is a really great publicly available dataset from the Texas Cancer Research Biobank (http://txcrb.org/sequencing.html). We have created a step by step list of instructions that guide users through the workflow. In addition we have updated the README documentation to add a little more clarity. 

One last thing that we'd like to point out is that we have created a docker container (https://hub.docker.com/r/eagenomics/cnvradar) that can be used for running the CNV Radar. You will need to download the appropriate dbSNP annotation file and map them to the docker. This was going to go into the docker but it was too large. 

hg19
ftp://ftp.ncbi.nih.gov/snp/organisms/human_9606_b151_GRCh37p13/VCF/All_20180423.vcf.gz ftp://ftp.ncbi.nih.gov/snp/organisms/human_9606_b151_GRCh37p13/VCF/All_20180423.vcf.gz.tbi 

hg38
ftp://ftp.ncbi.nih.gov/snp/organisms/human_9606_b151_GRCh38p7/VCF/All_20180418.vcf.gz ftp://ftp.ncbi.nih.gov/snp/organisms/human_9606_b151_GRCh38p7/VCF/All_20180418.vcf.gz.tbi 

The vignette shows how to download the hg19 dbSNP annotations and run the tool. 
Download: https://github.com/ExpressionAnalysis/CNV_Radar/blob/master/Vignette/vignette.md#retrieve-the-variant-annotations
Annotate VCF: https://github.com/ExpressionAnalysis/CNV_Radar/blob/master/Vignette/vignette.md#annotate-the-vcf-file

Hopefully these new resources will make the tool a bit easier to run. Please let us know if there are any further issues and we'll work to address them. 

Regards,
Jeran

**Comment by janrehker** [comment]
Thanks a bunch for the tutorial!

We'll give it a second shot.
